### ISSUE TITLE
WTF is this star? KIC 5217733

### ISSUE THREAD

**Issue by adrn** [adrn/ebak#13]
Does anybody know anything about stars? @mkness

**Comment by mkness** [comment]
hot main sequence star; ( & ASPCAP model looks reasonable enough). You can find the main sequence parameters in the FPARAM column of the allStar file:  Teff = 7.31629980e+03 (K),   logg = 4.98559999e+00 for this star (the stars with log g < 3.9 are giants). I have no idea which files you guys are working with but I'm assuming 1) the apStar fits files which have the individual visits & the synthetic spectral in the third dimension of the array and the allStar (v603) fits file which has the summary stellar parameters? Anyways,  anything that looks like this without lines and broad features is probably a hot main sequence star. I only ever find main sequence stars to throw them out of my analyses, I don't know much about them in detail.

**Comment by davidwhogg** [comment]
but why are the lines so broad -- is that normal?

**Comment by mkness** [comment]
yes. just plot more stars around that temperature. rotation broadening is my guess (but I don't know anything about these really).
