### ISSUE TITLE
are we using dr12 or dr13?

### ISSUE THREAD

**Issue by davidwhogg** [adrn/ebak#30]
- [ ] make a decision
- [ ] make sure the code and text both reflect this decision
- [ ] cite the correct literature

**Comment by mkness** [comment]
What will help make the decision? The number of stars in DR13 and DR12 is nominally the same. There are differences in the way reductions are handled including the way the LSF was dealt with i.e. DR12 a single LSF is assumed DR13 it is broken up into a number of different bins. I expect this won't make too much difference.

**Comment by adrn** [comment]
Moved to adrn/thejoker#1
