### ISSUE TITLE
get @dfm to predict RV vs time

### ISSUE THREAD

**Issue by davidwhogg** [adrn/ebak#4]
This is a simple (maybe already-done?) modification to @dfm's transit code, no?

**Comment by davidwhogg** [comment]
this is back in @davidwhogg's court

**Comment by davidwhogg** [comment]
I am going to do this but @dfm can you point me to where in your code you solve for f, E, given M? I need those functions for my solve of df/dt given dM/dt

**Comment by dfm** [comment]
I do it here: https://github.com/dfm/transit/blob/master/transit/include/kepler.h#L20

You might just want to do it yourself in Python cause it would be a PITA to use this.

**Comment by davidwhogg** [comment]
I just implemented everything here https://github.com/adrn/ebak/blob/master/ebak/celestialmechanics.py
I am very proud of myself! But this code is untested. Closing this issue and about to open two others.
